#include <math.h>
#include <emscripten/emscripten.h>
#include <wasm_simd128.h>
//#include <wasm_simd.h>
#include <string.h>

// Linear interpolation between x and y at fraction z (z in [0, 1])
static inline float interpolate(float x, float y, float z) {
	return x + (y - x) * z;
};

static inline double interpolateD(double x, double y, double z) {
	return x + (y - x) * z;
};

// audioData: pointer to input samples in WASM memory (read-only here)
// outData:   pointer to a separate output buffer.
// len:	   sample count (same for audioData and outData)
// sampleRate: in Hz
// volume:	0-100+ (the wetness volume)
// rate:	  LFO rate in Hz
// depth:	 max delay in seconds (e.g. 0.003 for 3ms)
// antiAliasing: 1 for interpolated (smooth) delay, 0 for truncated (fast/aliased)

// This was written with the help of Claude Sonnet 4.6.
EMSCRIPTEN_KEEPALIVE
void chorus_process(const float* audioData, float* outData, int len, int sampleRate, float volume, float rate, float depth, int antiAliasing) {
	if (volume == 0.0f || len <= 0) return;

	const float dryMix = 1.0f;
	const float wetMix = volume * 0.01f;

	const float depthSamples = depth * (float)sampleRate;

	float phase = (float)M_PI / 2.0f;
	const float pi2 = 2.0f * (float)M_PI;
	const float phaseIncrement = pi2 * rate / (float)sampleRate;

	float delaySamples, readIndex, delayedSample;
	int intIndex;

	if (antiAliasing) {
		for (int i = 0; i < len; i++) {
			delaySamples = (sinf(phase) * 0.5f + 0.5f) * depthSamples;
			readIndex = (float)i - delaySamples;

			intIndex = (int)readIndex; // truncation toward zero, matches JS `| 0` for non-negative values

			if (readIndex >= 0.0f) {
				float a = audioData[intIndex];

				// Clamp the +1 tap to the last sample instead of reading out of bounds
				float b = (intIndex + 1 < len) ? audioData[intIndex + 1] : audioData[len - 1];
				float frac = readIndex - (float)intIndex; // equivalent to JS `readIndex % 1` for readIndex >= 0
				delayedSample = interpolate(a, b, frac);
			} else {
				delayedSample = 0.0f;
			}

			outData[i] = dryMix * audioData[i] + wetMix * delayedSample;

			phase += phaseIncrement;
			if (phase > pi2) phase -= pi2;
		}
	} else {
		for (int i = 0; i < len; i++) {
			delaySamples = (float)(int)((sinf(phase) * 0.5f + 0.5f) * depthSamples);
			int readIndexInt = i - (int)delaySamples;

			delayedSample = (readIndexInt >= 0) ? audioData[readIndexInt] : 0.0f;

			outData[i] = dryMix * audioData[i] + wetMix * delayedSample;

			phase += phaseIncrement;
			if (phase > pi2) phase -= pi2;
		}
	}
};

// This was the reference I was talking about, written by GPT-5.3 Mini. It almost got my brain stuck on one part, especially with the cryptic variable names.
inline float triangle_reflect_range(float x, float min, float max) {
	float S = max - min;
	float T = 2.0f * S;

	float u = x - min;

	// fast modulo approximation (works well when floor is acceptable)
	float m = u - T * floorf(u / T);

	float d = m - S;
	float tri = S - fabsf(d);

	return min + tri;
};

// This was the reference that I used to implement the SIMD-ified version. This was generated by Claude Sonnet 4.6
inline float wrap_range(float x, float min, float max) {
	float range = max - min;
	float offset = x - min;
	float wrapped = offset - range * floorf(offset / range);
	return min + wrapped;
};

EMSCRIPTEN_KEEPALIVE
void dcoffset_process(float* audioData, int len, float dcOffset, size_t vectorized_size) {
	size_t i = 0;

	if (dcOffset != 0.0f) {
		v128_t dcoffset_vector = wasm_f32x4_splat(dcOffset);

		for (; i < vectorized_size; i += 4) {
			float* p = audioData + i;
			// Load 4 floats from memory into a SIMD register, and
			// store the 4 results back into memory
			wasm_v128_store(p, wasm_f32x4_add(wasm_v128_load(p), dcoffset_vector));
		}

		for (; i < len; ++i) {
			audioData[i] += dcOffset;
		}
	}
}

// audioData: pointer to input samples in WASM memory (mutable here)
// len: length of audioData
// volume: the multiplier of the audio data
// clipMode: 0 = no clipping (1.0 stays 1.0, 3.0 stays 3.0, 248.0 stays 248.0, -2.34 stays -2.34)
// 1 = clamping (1.0 stays 1.0, 1.5 becomes 1.0, 9.0 becomes 1.0, -0.2 stays -0.2, -1.0 stays -1.0, -4.0 becomes -1.0)
// 2 = warp around (1.0 becomes -1.0, 1.2 becomes -0.8, 2.0 becomes 0, 802.0 becomes 0.0, -1.2 becomes 0.8, -1.5 becomes 0.5)
// 3 = triangular bouncing (1.0 stays 1.0, 1.2 becomes 0.8, 1.5 becomes 0.5, 1.8 becomes 0.2, 2.0 becomes 0.0, 2.5 becomes -0.5)
// clipMin & clipMax: self explanatory?

// This was written using the help of Gemini, but with major modifications to the original code, and a good understanding of the SIMD instructions.
EMSCRIPTEN_KEEPALIVE
void gain_process(float* audioData, int len, float volume, int clipMode, float clipMin, float clipMax, float dcOffset, int dcOffsetBeforeGain, int handleNaNs) {
	size_t i = 0;

	size_t vectorized_size = len & ~3; // Equivalent to (size / 4) * 4;
	bool canHandleDCOffset = !dcOffsetBeforeGain;

	if (volume == 0.0f) {
		if (canHandleDCOffset && dcOffset != 0.0f) {
			if (handleNaNs) {
				v128_t dcoffset_vector = wasm_f32x4_splat(dcOffset);
				canHandleDCOffset = false;
				for (; i < vectorized_size; i += 4) {
					float* p = audioData + i;
					v128_t data_vector = wasm_v128_load(p);

					v128_t is_equal = wasm_f32x4_eq(data_vector, data_vector);

					// Set all 4 elements to the DC Offset if they're not NaNs simultaneously, and
					// store the 4 results back into memory
					wasm_v128_store(p, wasm_i8x16_relaxed_laneselect(data_vector, dcoffset_vector, is_equal));
				}

				// 3. Clean up the "remainder" elements if 'size' isn't a multiple of 4
				for (; i < len; ++i) {
					if (audioData[i] == audioData[i]) audioData[i] = dcOffset;
				}
			}
		} else if (dcOffset == 0.0f) {
			canHandleDCOffset = false;
			if (handleNaNs) {
				for (; i < vectorized_size; i += 4) {
					float* p = audioData + i;
					v128_t data_vector = wasm_v128_load(p);

					v128_t is_equal = wasm_f32x4_eq(data_vector, data_vector);

					// Set all 4 elements to 0 if they're not NaNs simultaneously, and
					// store the 4 results back into memory
					wasm_v128_store(p, wasm_v128_and(data_vector, is_equal));
				}

				// 3. Clean up the "remainder" elements if 'size' isn't a multiple of 4
				for (; i < len; ++i) {
					if (audioData[i] == audioData[i]) audioData[i] = 0.0f;
				}
			} else memset(audioData, 0, len * sizeof(float)); // Zeroes out the samples by filling bytes with 0s (unsafe, but works due to how Float32 is structured)
		}
		return;
	}

	// 1. Duplicate the float across all 4 slots of a 128-bit vector
	v128_t scalar_vector = wasm_f32x4_splat(volume);

	// 2. Process elements in batches of 4

	if (dcOffsetBeforeGain && canHandleDCOffset && (clipMode != 0 || volume == 1.0f)) {
		dcoffset_process(audioData, len, dcOffset, vectorized_size);
		canHandleDCOffset = false;
	} // Can be optimized without processing via `dcoffset_process` (another loop)

	if (volume == 0.0f && clipMode == 0) return;

	if (clipMode == 0 && volume != 1.0f) {
		if (canHandleDCOffset && dcOffset != 0.0f) {
			v128_t dcoffset_vector = wasm_f32x4_splat(dcOffset);

			canHandleDCOffset = false;

			if (volume == -1.0f) {
				for (; i < vectorized_size; i += 4) {
					float* p = audioData + i;
					v128_t data_vector = wasm_v128_load(p);

					// Negate all 4 elements simultaneously, and
					// store the 4 results back into memory
					wasm_v128_store(p, wasm_f32x4_add(wasm_f32x4_neg(data_vector), dcoffset_vector));
				}

				// 3. Clean up the "remainder" elements if 'size' isn't a multiple of 4
				for (; i < len; ++i) {
					audioData[i] = -audioData[i] + dcOffset;
				}
			} else {
				for (; i < vectorized_size; i += 4) {
					float* p = audioData + i;
					v128_t data_vector = wasm_v128_load(p);

					// Multiply all 4 elements simultaneously, then
					// store the 4 results back into memory
					wasm_v128_store(p, __builtin_wasm_relaxed_madd_f32x4(data_vector, scalar_vector, dcoffset_vector));
				}

				// 3. Clean up the "remainder" elements if 'size' isn't a multiple of 4
				for (; i < len; ++i) {
					audioData[i] = audioData[i] * volume + dcOffset;
				}
			}
		} else {
			if (volume == -1.0f) {
				for (; i < vectorized_size; i += 4) {
					float* p = audioData + i;
					v128_t data_vector = wasm_v128_load(p);

					// Negate all 4 elements simultaneously, and
					// store the 4 results back into memory
					wasm_v128_store(p, wasm_f32x4_neg(data_vector));
				}

				// 3. Clean up the "remainder" elements if 'size' isn't a multiple of 4
				for (; i < len; ++i) {
					audioData[i] = -audioData[i];
				}
			} else {
				for (; i < vectorized_size; i += 4) {
					float* p = audioData + i;
					v128_t data_vector = wasm_v128_load(p);

					// Multiply all 4 elements simultaneously, then
					// store the 4 results back into memory
					wasm_v128_store(p, wasm_f32x4_mul(data_vector, scalar_vector));
				}

				// 3. Clean up the "remainder" elements if 'size' isn't a multiple of 4
				for (; i < len; ++i) {
					audioData[i] *= volume;
				}
			}
		}
	} else if (clipMode == 1) {
		v128_t min_vector = wasm_f32x4_splat(clipMin);
		v128_t max_vector = wasm_f32x4_splat(clipMax);

		if (volume == 1.0f) {
			for (; i < vectorized_size; i += 4) {
				float* p = audioData + i;
				// Load 4 floats from memory into a SIMD register
				v128_t result_vector = wasm_v128_load(p);

				// Clamp the samples within the range
				result_vector = wasm_f32x4_max(result_vector, min_vector);
				result_vector = wasm_f32x4_min(result_vector, max_vector);

				// Store the 4 results back into memory
				wasm_v128_store(p, result_vector);
			}

			for (; i < len; i++) {
				if (audioData[i] < clipMin) audioData[i] = clipMin; else if (audioData[i] > clipMax) audioData[i] = clipMax;
			}
		} else {
			for (; i < vectorized_size; i += 4) {
				float* p = audioData + i;
				// Load 4 floats from memory into a SIMD register
				v128_t result_vector = wasm_v128_load(p);

				// Multiply all 4 elements simultaneously
				result_vector = wasm_f32x4_mul(result_vector, scalar_vector);

				// Clamp the samples within the range
				result_vector = wasm_f32x4_max(result_vector, min_vector);
				result_vector = wasm_f32x4_min(result_vector, max_vector);

				// Store the 4 results back into memory
				wasm_v128_store(p, result_vector);
			}

			for (; i < len; i++) {
				audioData[i] *= volume;
				if (audioData[i] < clipMin) audioData[i] = clipMin; else if (audioData[i] > clipMax) audioData[i] = clipMax;
			}
		}
	} else if (clipMode == 2) {
		v128_t v_one = wasm_f32x4_splat(1.0f);
		v128_t v_two = wasm_f32x4_splat(2.0f);
		v128_t v_half = wasm_f32x4_splat(0.5f);

		if (clipMin == -1.0f && clipMax == 1.0f) {
		if (volume == 1.0f) {
			for (; i < vectorized_size; i += 4) {
				float* p = audioData + i;
				// Load 4 floats from memory into a SIMD register
				v128_t data_vector = wasm_v128_load(p);

				// Shift the elements by +1.0 (range is now [0.0, 2.0])
				v128_t shifted = wasm_f32x4_add(data_vector, v_one);

				// Compute modulo via shifted - (floor(shifted / 2.0) * 2.0)

				// Divide elements by 2.0 (range is now [0.0, 1.0])
				v128_t div_two = wasm_f32x4_mul(shifted, v_half);

				// Floor the elements (yes, there's a native floor SIMD instruction)
				v128_t result_vector = wasm_f32x4_floor(div_two);

				// Multiply the floored elements by 2.0
				result_vector        = wasm_f32x4_mul(result_vector, v_two);

				// Subtract the shifted elements by the modded ones
				result_vector  = wasm_f32x4_sub(shifted, result_vector);

				// Shift range from [0, 2] back to [-1, 1]
				result_vector = wasm_f32x4_sub(result_vector, v_one);

				// Store the 4 results back into memory
				wasm_v128_store(p, result_vector);
			}

			for (; i < len; ++i) {
				// Scalar fallback logic
				float shifted = audioData[i] + 1.0f;
				float modded = shifted - (floorf(shifted * 0.5f) * 2.0f);

				audioData[i] = modded - 1.0f;
			}
		} else {
			for (; i < vectorized_size; i += 4) {
				float* p = audioData + i;
				// Load 4 floats from memory into a SIMD register
				v128_t data_vector = wasm_v128_load(p);

				// Multiply all 4 elements simultaneously
				data_vector = wasm_f32x4_mul(data_vector, scalar_vector);

				// Shift the elements by +1.0 (range is now [0.0, 2.0])
				data_vector = wasm_f32x4_add(data_vector, v_one);

				// Compute modulo via shifted - (floor(shifted / 2.0) * 2.0)

				// Divide elements by 2.0 (range is now [0.0, 1.0])
				v128_t div_two = wasm_f32x4_mul(data_vector, v_half);

				// Floor the elements (yes, there's a native floor SIMD instruction)
				v128_t result_vector = wasm_f32x4_floor(div_two);

				// Multiply the floored elements by 2.0
				result_vector        = wasm_f32x4_mul(result_vector, v_two);

				// Subtract the shifted elements by the modded ones
				result_vector = wasm_f32x4_sub(data_vector, result_vector);

				// Shift range from [0, 2] back to [-1, 1]
				result_vector = wasm_f32x4_sub(result_vector, v_one);

				// Store the 4 results back into memory
				wasm_v128_store(p, result_vector);
			}

			for (; i < len; ++i) {
				// Scalar fallback logic
				float shifted = audioData[i] * volume + 1.0f;
				float modded = shifted - (floorf(shifted * 0.5f) * 2.0f);

				audioData[i] = modded - 1.0f;
			}
		}} else {
		v128_t min_vector = wasm_f32x4_splat(clipMin);
		v128_t max_vector = wasm_f32x4_splat(clipMax);

		v128_t ran_vector = wasm_f32x4_sub(max_vector, min_vector);

		v128_t reciprocal_vector = wasm_f32x4_div(v_one, ran_vector);

		if (volume == 1.0f) {
			for (; i < vectorized_size; i += 4) {
				float* p = audioData + i;
				// Load 4 floats from memory into a SIMD register
				v128_t offset_vector = wasm_v128_load(p);

				// Calculate the offset
				offset_vector = wasm_f32x4_sub(offset_vector, min_vector);

				v128_t offset_div_vector = wasm_f32x4_mul(offset_vector, reciprocal_vector);

				offset_div_vector = wasm_f32x4_floor(offset_div_vector);

				//offset_div_vector = wasm_f32x4_add(wasm_f32x4_mul(offset_div_vector, ran_vector), offset_vector);

				offset_div_vector = __builtin_wasm_relaxed_madd_f32x4(offset_div_vector, ran_vector, offset_vector);

				offset_div_vector = wasm_f32x4_add(offset_div_vector, min_vector);

				// Store the 4 results back into memory
				wasm_v128_store(p, offset_div_vector);
			}

			for (; i < len; ++i) {
				audioData[i] = wrap_range(audioData[i], clipMin, clipMax);
			}
		} else {
			for (; i < vectorized_size; i += 4) {
				float* p = audioData + i;
				// Load 4 floats from memory into a SIMD register
				v128_t offset_vector = wasm_v128_load(p);

				offset_vector = wasm_f32x4_mul(offset_vector, scalar_vector);

				// Calculate the offset
				offset_vector = wasm_f32x4_sub(offset_vector, min_vector);

				v128_t offset_div_vector = wasm_f32x4_mul(offset_vector, reciprocal_vector);

				offset_div_vector = wasm_f32x4_floor(offset_div_vector);

				//offset_div_vector = wasm_f32x4_add(wasm_f32x4_mul(offset_div_vector, ran_vector), offset_vector);

				offset_div_vector = __builtin_wasm_relaxed_madd_f32x4(offset_div_vector, ran_vector, offset_vector);

				offset_div_vector = wasm_f32x4_add(offset_div_vector, min_vector);

				// Store the 4 results back into memory
				wasm_v128_store(p, offset_div_vector);
			}

			for (; i < len; ++i) {
				audioData[i] = wrap_range(audioData[i] * volume, clipMin, clipMax);
			}
		}}
	} else if (clipMode == 3) { // This is implemented manually via SIMD, but I did receive a reference of an un-SIMD'd implementation (from GPT-5.3 Mini)
		v128_t min_vector = wasm_f32x4_splat(clipMin);
		v128_t max_vector = wasm_f32x4_splat(clipMax);

		v128_t ran_vector = wasm_f32x4_sub(max_vector, min_vector);

		v128_t v_one = wasm_f32x4_splat(1.0f);
		v128_t v_two = wasm_f32x4_splat(2.0f);

		v128_t ran2_vector = wasm_f32x4_mul(ran_vector, v_two);
		v128_t reciprocal_vector = wasm_f32x4_div(v_one, ran2_vector);

		if (volume == 1.0f) {
			for (; i < vectorized_size; i += 4) {
				float* p = audioData + i;
				// Load 4 floats from memory into a SIMD register
				v128_t shifted = wasm_v128_load(p);

				// Shift the elements down by the minimum limit (element - min)
				shifted = wasm_f32x4_sub(shifted, min_vector);

				// Multiply the shifted elements by the `reciprocal` (faster) (shifted / S) S = max - min
				v128_t mult_flr = wasm_f32x4_mul(shifted, reciprocal_vector);

				// Floor the multiplied elements
				mult_flr = wasm_f32x4_floor(mult_flr);

				// Multiply the floored elements by `T` (flr * T) T = max - min, and
				// Shift the elements up by `shifted` (trishift + u) `shifted` = `data_vector` - min
				//v128_t trishift = wasm_f32x4_sub(shifted, wasm_f32x4_mul(mult_flr, ran2_vector));

				v128_t trishift = __builtin_wasm_relaxed_nmadd_f32x4(mult_flr, ran2_vector, shifted);

				// Shift `shifted_trishift` down by S (shifted_trishift + S) `S` = max - min
				trishift = wasm_f32x4_sub(trishift, ran_vector);

				// Absolute
				trishift = wasm_f32x4_abs(trishift);

				// Triangular
				trishift = wasm_f32x4_sub(ran_vector, trishift);

				trishift = wasm_f32x4_add(trishift, min_vector);

				// Store the 4 results back into memory
				wasm_v128_store(p, trishift);
			}

			for (; i < len; ++i) {
				audioData[i] = triangle_reflect_range(audioData[i], clipMin, clipMax);
			}
		} else {
			for (; i < vectorized_size; i += 4) {
				float* p = audioData + i;
				// Load 4 floats from memory into a SIMD register
				v128_t shifted = wasm_v128_load(p);

				shifted = wasm_f32x4_mul(shifted, scalar_vector);

				// Shift the elements down by the minimum limit (element - min)
				shifted = wasm_f32x4_sub(shifted, min_vector);

				// Multiply the shifted elements by the `reciprocal` (faster) (shifted / S) S = max - min
				v128_t mult_flr = wasm_f32x4_mul(shifted, reciprocal_vector);

				// Floor the multiplied elements
				mult_flr = wasm_f32x4_floor(mult_flr);

				// Multiply the floored elements by `T` (flr * T) T = max - min, and
				// Shift the elements up by `shifted` (trishift + u) `shifted` = `data_vector` - min
				//v128_t trishift = wasm_f32x4_sub(shifted, wasm_f32x4_mul(mult_flr, ran2_vector));

				v128_t trishift = __builtin_wasm_relaxed_nmadd_f32x4(mult_flr, ran2_vector, shifted);

				// Shift `shifted_trishift` down by S (shifted_trishift + S) `S` = max - min
				trishift = wasm_f32x4_sub(trishift, ran_vector);

				// Absolute
				trishift = wasm_f32x4_abs(trishift);

				// Triangular
				trishift = wasm_f32x4_sub(ran_vector, trishift);

				trishift = wasm_f32x4_add(trishift, min_vector);

				// Store the 4 results back into memory
				wasm_v128_store(p, trishift);
			}

			for (; i < len; ++i) {
				audioData[i] = triangle_reflect_range(audioData[i] * volume, clipMin, clipMax);
			}
		}
	}

	// I put this into a separate loop.
	if (!dcOffsetBeforeGain && canHandleDCOffset) dcoffset_process(audioData, len, dcOffset, vectorized_size);
}

static float TWOPI = 2.0f * (float)M_PI; 
static float sqrtTwo = 1.4142135381698608f;

enum BiquadFilterType : unsigned int {
	BI_LOWPASS = 0, BI_HIGHPASS = 1, BI_BANDPASS = 2, BI_PEAK = 3, BI_NOTCH = 4, BI_LOWSHELF = 5, BI_HIGHSHELF = 6, BI_ALLPASS = 7, BI_SALLENKEY_LOWPASS = 8, BI_SALLENKEY_HIGHPASS = 9
};


enum BiquadFilterForm : unsigned int {
	BI_FORM_II_TRANS = 0, BI_FORM_II = 1, BI_FORM_I_TRANS = 2, BI_FORM_I = 3
};

void CALCULATE_BIQUAD_FREQ_COEFFICIENTS(float* coefficients, float sampleRate, float cutoffFreq, float doubleQuality, enum BiquadFilterType type, float gain, float poleRadius) { // Most of this function was written using GPT-5.3 and GPT-5.3 Mini (for the mathematical formulas)
	// The gain is for Peak / Lowshelf / Highshelf.
	// The pole radius is for the notch.

	float b0 = 0.0f, b1 = 0.0f, b2 = 0.0f, a0 = 0.0f, a1 = 0.0f, a2 = 0.0f;

	float angFreq = TWOPI * cutoffFreq / sampleRate;

	float sinw = sinf(angFreq);

	float filterGain = sinw / doubleQuality;

	float cosw = cosf(angFreq);

	float A = powf(10.0, gain * 0.025f); // Used for Peak / Lowshelf / Highshelf (gain / 40.0f)

	float K = tanf(angFreq * 0.5f); // For the Sallen Key Lowpass type

	switch (type) {
		case BI_LOWPASS: { // Lowpass discards higher frequencies, or makes them quieter.
			float oneMinusCW = 1.0f - cosw;

			b0 = oneMinusCW * 0.5f;
			b1 = oneMinusCW;
			b2 = oneMinusCW * 0.5f;
			a0 = 1.0f + filterGain;
			a1 = -2.0f * cosw;
			a2 = 1.0f - filterGain;
			break;
		}
		case BI_HIGHPASS: { // Highpass discards lower frequencies, or makes them quieter.
			float onePlusCW = 1.0f + cosw;

			b0 = onePlusCW * 0.5f;
			b1 = -onePlusCW;
			b2 = onePlusCW * 0.5f;
			a0 = 1.0f + filterGain;
			a1 = -2.0f * cosw;
			a2 = 1.0f - filterGain;
			break;
		}
		case BI_BANDPASS: { // Bandpass discards very low frequencies, and very high frequencies, or makes them quieter. The b* coefficients were fixed by GPT-5.5
			b0 = filterGain;
			b1 = 0.0f;
			b2 = -filterGain;
			a0 = 1.0f + filterGain;
			a1 = -2.0f * cosw;
			a2 = 1.0f - filterGain;
			break;
		}
		case BI_PEAK: { // gain > 0 = boost, gain < 0 = cut. Peak boosts, or amplifies a specific frequency.
			float alphaTA = filterGain * A;
			float alphaDA = filterGain / A;
			float negDoubleCosW = -2.0f * cosw;

			b0 = 1.0f + alphaTA;
			b1 = negDoubleCosW;
			b2 = 1.0f - alphaTA;
			a0 = 1.0f + alphaDA;
			a1 = negDoubleCosW;
			a2 = 1.0f - alphaDA;
			break;
		}
		case BI_NOTCH: { // Notch quiets down a specific frequency, or nearly eliminates it. implementation: the surrounding frequencies are nearly zeroed out, or attenuated quite a lot
			float negDoubleCosW = -2.0f * cosw;

			b0 = 1.0f;
			b1 = negDoubleCosW;
			b2 = 1.0f;
			a0 = 1.0f;
			a1 = negDoubleCosW * poleRadius;
			a2 = poleRadius * poleRadius;
			break;
		}
		case BI_LOWSHELF: {
			float sqrtA = sqrtf(A);
			float twoSqrtAAlpha = 2.0f * sqrtA * filterGain ;

			float incA = A + 1.0f;
			float decA = A - 1.0f;

			float decACosW = decA * cosw;

			float intapDecacosw = incA + decACosW;
			float intamDecacosw = incA - decACosW;

			float incaCosw = incA * cosw;

			b0 = A * (intamDecacosw + twoSqrtAAlpha);
			b1 = 2.0f * A * (decA - incaCosw);
			b2 = A * (intamDecacosw - twoSqrtAAlpha);
			a0 = intapDecacosw + twoSqrtAAlpha;
			a1 = -2.0f * (decA + incaCosw);
			a2 = intapDecacosw - twoSqrtAAlpha;
			break;
		}
		case BI_HIGHSHELF: {
			float sqrtA = sqrtf(A);
			float twoSqrtAAlpha = 2.0f * sqrtA * filterGain ;

			float incA = A + 1.0f;
			float decA = A - 1.0f;

			float decACosW = decA * cosw;

			float intapDecacosw = incA + decACosW;
			float intamDecacosw = incA - decACosW;

			float incaCosw = incA * cosw;

			b0 = A * (intapDecacosw + twoSqrtAAlpha);
			b1 = -2.0f * A * (decA + incaCosw);
			b2 = A * (intapDecacosw - twoSqrtAAlpha);
			a0 = intamDecacosw + twoSqrtAAlpha;
			a1 = 2.0f * (decA - incaCosw);
			a2 = intamDecacosw - twoSqrtAAlpha;
			break;
		}
		case BI_ALLPASS: { // This part of the code was written by Grok
			// Inside your coefficient calculation function (in WASM or JS)
			double alpha = sin(angFreq) / doubleQuality;   // or use your existing pole radius logic

			// All-Pass coefficients
			b0 = 1.0 - alpha;
			b1 = -2.0 * cos(angFreq);
			b2 = 1.0 + alpha;

			a0 = 1.0 + alpha;
			a1 = b1;
			a2 = 1.0 - alpha;
			break;
		}
		case BI_SALLENKEY_LOWPASS: {
			float kSquared = K * K;
			float kSqrt = sqrtTwo * K + kSquared;

			float kIncSqrt = 1.0f + kSqrt;
			float kIncNegSqrt = 1.0f - kSqrt;

			b0 = kSquared / kIncSqrt;
			b1 = 2.0f * b0;
			b2 = b0;
			a0 = 1.0f;
			a1 = 2.0f * (kSquared - 1.0f) / kIncSqrt;
			a2 = kIncNegSqrt / kIncSqrt;
			break;
		}
		case BI_SALLENKEY_HIGHPASS: {
			float kSquared = K * K;
			float kSqrt = sqrtTwo * K + kSquared;
			float kIncSqrt = 1.0f + kSqrt;
			float kIncNegSqrt = 1.0f - kSqrt;

			b0 = 1.0f / kIncSqrt;
			b1 = -2.0f / kIncSqrt;
			b2 = b0;
			a0 = 1.0f;
			a1 = 2.0f * (kSquared - 1.0f) / kIncSqrt;
			a2 = kIncNegSqrt / kIncSqrt;
			break;
		}
	}

	if (a0 == 1.0f) {
		coefficients[0] = b0;
		coefficients[1] = b1;
		coefficients[2] = b2;
		coefficients[3] = 1.0f;
		coefficients[4] = a1;
		coefficients[5] = a2;
	} else {
		float invA0 = 1.0f / a0;

		coefficients[0] = b0 * invA0;
		coefficients[1] = b1 * invA0;
		coefficients[2] = b2 * invA0;
		coefficients[3] = 1.0f;
		coefficients[4] = a1 * invA0;
		coefficients[5] = a2 * invA0;
	}
};

struct BIQUAD_FREQ_FILTER {
/*
public:
	BIQUAD_FREQ_FILTER(IN b0, IN b1, IN b2, IN a1, IN a2) : b0(b0), b1(b1), b2(b2), a1(a1), a2(a2), x1(0), x2(0), y1(0), y2(0) {}

	void setCoefficients(IN nb0, IN nb1, IN nb2, IN na1, IN na2) {
		b0 = nb0; b1 = nb1; b2 = nb2; a1 = na1; a2 = na2;
	}

	OUT process(OUT x) {
		IN y = b0 * x + b1 * x1 + b2 * x2 - a1 * y1 - a2 * y2;

		// Shift state variables (delays)
		x2 = x1;
		x1 = x;
		y2 = y1;
		y1 = y;

		return (OUT)y;
	}

	void reset() { z1 = z2 = IN(0); }

private:*/
	float b0, b1, b2, a1, a2; // Feedforward
	float x1, x2; // Input delays (x[n-1], x[n-2])
	float y1, y2; // Output delays (y[n-1], y[n-2])
	float w1, w2;
	float z1, z2;
};

inline void BIQUAD_FREQ_FILTER_setCoefficients(float* coefficients, struct BIQUAD_FREQ_FILTER* biquadFilter) {
	biquadFilter->b0 = coefficients[0];biquadFilter->b1 = coefficients[1];biquadFilter->b2 = coefficients[2];biquadFilter->a1 = coefficients[4];biquadFilter->a2 = coefficients[5];
};

// Function to process a single audio sample, written using the help of Gemini
inline float BIQUAD_FREQ_FILTER_I_TRANS_process(float sample, struct BIQUAD_FREQ_FILTER* biquadFilter) {
	// Calculate the output
	float output = biquadFilter->b0 * sample + biquadFilter->b1 * biquadFilter->x1 + biquadFilter->b2 * biquadFilter->x2 - biquadFilter->a1 * biquadFilter->y1 - biquadFilter->a2 * biquadFilter->y2;

	// Shift the delay lines for the next cycle
	biquadFilter->x2 = biquadFilter->x1;
	biquadFilter->x1 = sample;
	biquadFilter->y2 = biquadFilter->y1;
	biquadFilter->y1 = output;

	return output;
}

inline float BIQUAD_FREQ_FILTER_I_process(float sample, struct BIQUAD_FREQ_FILTER* biquadFilter) {
	float y = biquadFilter->b0 * sample + biquadFilter->b1 * biquadFilter->x1 + biquadFilter->b2 * biquadFilter->x2 - biquadFilter->a1 * biquadFilter->y1 - biquadFilter->a2 * biquadFilter->y2;

	// Shift state variables (delays)
	biquadFilter->x2 = biquadFilter->x1;
	biquadFilter->x1 = sample;
	biquadFilter->y2 = biquadFilter->y1;
	biquadFilter->y1 = y;

	return y;
};

inline float BIQUAD_FREQ_FILTER_II_TRANS_process(float sample, struct BIQUAD_FREQ_FILTER* biquadFilter) {
	float y = biquadFilter->b0 * sample + biquadFilter->z1;

	biquadFilter->z1 = biquadFilter->b1 * sample - biquadFilter->a1 * y + biquadFilter->z2;
	biquadFilter->z2 = biquadFilter->b2 * sample - biquadFilter->a2 * y;

	return y;
};

/*	OUT process(OUT x) {
		IN y = b0 * x + z1;
		z1 = b1 * x - a1 * y + z2;
		z2 = b2 * x - a2 * y;
		return (OUT)y;
	}*/

inline float BIQUAD_FREQ_FILTER_II_process(float sample, struct BIQUAD_FREQ_FILTER* biquadFilter) {
	float w = sample - biquadFilter->a1 * biquadFilter->w1 - biquadFilter->a2 * biquadFilter->w2;
	float y = biquadFilter->b0 * w + biquadFilter->b1 * biquadFilter->w1 + biquadFilter->b2 * biquadFilter->w2;

	biquadFilter->w2 = biquadFilter->w1;
	biquadFilter->w1 = w;

	return y;
};

/*	OUT process(OUT x) {
		IN w = x - a1 * w1 - a2 * w2;
		IN y = b0 * w + b1 * w1 + b2 * w2;

		w2 = w1;
		w1 = w;

		return (OUT)y;
	}*/

// NOTE: Gain is only additive, not a multiplier.

const int samplesCrossfadeBiquadFrequencyFilter = 32;
const float samplesCrossfadeInverse = 1.0f / samplesCrossfadeBiquadFrequencyFilter;

const int numOfParamsPerBiquadPoint = 2;

EMSCRIPTEN_KEEPALIVE
void biquadfrequencyfilter_i_process(float* buffer, int len, float sampleRate, float cutoffFreq, float quality, enum BiquadFilterType type, float gain, float poleRadius, enum BiquadFilterForm form, bool crossFade, const float* points, int numberOfPoints) {
	if (len <= 1) return;

	float coefficients[6];

	float doubleQuality = quality * 2.0f; // We made it so quality * 2 has to be passed for performance.

	CALCULATE_BIQUAD_FREQ_COEFFICIENTS(coefficients, sampleRate, cutoffFreq, doubleQuality, type, gain, poleRadius);

	struct BIQUAD_FREQ_FILTER filter;

	filter.x1 = 0.0f;
	filter.x2 = 0.0f;
	filter.y1 = 0.0f;
	filter.y2 = 0.0f;
	filter.w1 = 0.0f;
	filter.w2 = 0.0f;
	filter.z1 = 0.0f;
	filter.z2 = 0.0f;

	BIQUAD_FREQ_FILTER_setCoefficients(coefficients, &filter);

	if (points != NULL && numberOfPoints > 0) {
		int indexOfPointBefore = 0;
		int indexOfPointAfter = 0;

		int numOfPointsOff2 = numberOfPoints - 2;

		// THE VERY FIRST POINT IS AUTOMATICALLY INSERTED!!!

		// REMEMBER: First parameter of point = where it is (in samples)
		// Second parameter of point = the frequency (in Hz). Expected range is [0, sampleRate / 2]

		// All the points are sorted by where they are in samples.

		for (size_t i = numOfParamsPerBiquadPoint; i < numOfPointsOff2; i += numOfParamsPerBiquadPoint) {
			if (points[i] > 0) {
				indexOfPointBefore = i - numOfParamsPerBiquadPoint;
				indexOfPointAfter = i;
				break;
			}
		}

		double p1 = points[indexOfPointBefore];
		double p2 = points[indexOfPointAfter];

		double p1Freq = points[indexOfPointBefore+1];
		double p2Freq = points[indexOfPointAfter+1];

		float currentFrequency = cutoffFreq;
		float oldFrequency = currentFrequency;

		double t = 0.0;

		size_t start = 0;
		size_t end = len;

		if (crossFade) {
			start = samplesCrossfadeBiquadFrequencyFilter;
			end = len - samplesCrossfadeBiquadFrequencyFilter;

			float approxFreq = p1Freq + (-p1 / (p2 - p1)) * (p2Freq - p1Freq);

			currentFrequency = approxFreq;
			oldFrequency = currentFrequency;

			CALCULATE_BIQUAD_FREQ_COEFFICIENTS(coefficients, sampleRate, approxFreq, doubleQuality, type, gain, poleRadius);
			BIQUAD_FREQ_FILTER_setCoefficients(coefficients, &filter);

			float x = samplesCrossfadeInverse;

			if (form == BI_FORM_II_TRANS) {
				for (size_t i = 1; i < samplesCrossfadeBiquadFrequencyFilter; i++) {
					buffer[i] = interpolate(buffer[i], BIQUAD_FREQ_FILTER_II_TRANS_process(buffer[i], &filter), x);
					x += samplesCrossfadeInverse;
				}
			} else if (form == BI_FORM_II) {
				for (size_t i = 1; i < samplesCrossfadeBiquadFrequencyFilter; i++) {
					buffer[i] = interpolate(buffer[i], BIQUAD_FREQ_FILTER_II_process(buffer[i], &filter), x);
					x += samplesCrossfadeInverse;
				}
			} else if (form == BI_FORM_I_TRANS) {
				for (size_t i = 1; i < samplesCrossfadeBiquadFrequencyFilter; i++) {
					buffer[i] = interpolate(buffer[i], BIQUAD_FREQ_FILTER_I_TRANS_process(buffer[i], &filter), x);
					x += samplesCrossfadeInverse;
				}
			} else {
				for (size_t i = 1; i < samplesCrossfadeBiquadFrequencyFilter; i++) {
					buffer[i] = interpolate(buffer[i], BIQUAD_FREQ_FILTER_I_process(buffer[i], &filter), x);
					x += samplesCrossfadeInverse;
				}
			}
		}
		if (form == BI_FORM_II_TRANS) {
			for (size_t i = start; i < end; i++) {
				if (i > p2) {
					currentFrequency = p2Freq;
					indexOfPointBefore += numOfParamsPerBiquadPoint;
					indexOfPointAfter += numOfParamsPerBiquadPoint;
					p1 = points[indexOfPointBefore];
					p2 = points[indexOfPointAfter];
					p1Freq = points[indexOfPointBefore+1];
					p2Freq = points[indexOfPointAfter+1];
					t = ((double)i - p1) / (p2 - p1);
				} else {
					t = ((double)i - p1) / (p2 - p1);
					currentFrequency = p1Freq + t * (p2Freq - p1Freq);
				}
				if ((currentFrequency < 40) || fabsf(currentFrequency - oldFrequency) > 7) {
					CALCULATE_BIQUAD_FREQ_COEFFICIENTS(coefficients, sampleRate, currentFrequency, doubleQuality, type, gain, poleRadius);
					BIQUAD_FREQ_FILTER_setCoefficients(coefficients, &filter);
					oldFrequency = currentFrequency;
				}
				buffer[i] = BIQUAD_FREQ_FILTER_II_TRANS_process(buffer[i], &filter);
			}
		} else if (form == BI_FORM_II) {
			for (size_t i = start; i < end; i++) {
				if (i > p2) {
					currentFrequency = p2Freq;
					indexOfPointBefore += numOfParamsPerBiquadPoint;
					indexOfPointAfter += numOfParamsPerBiquadPoint;
					p1 = points[indexOfPointBefore];
					p2 = points[indexOfPointAfter];
					p1Freq = points[indexOfPointBefore+1];
					p2Freq = points[indexOfPointAfter+1];
					t = ((double)i - p1) / (p2 - p1);
				} else {
					t = ((double)i - p1) / (p2 - p1);
					currentFrequency = p1Freq + t * (p2Freq - p1Freq);
				}
				if ((currentFrequency < 40) || fabsf(currentFrequency - oldFrequency) > 7) {
					CALCULATE_BIQUAD_FREQ_COEFFICIENTS(coefficients, sampleRate, currentFrequency, doubleQuality, type, gain, poleRadius);
					BIQUAD_FREQ_FILTER_setCoefficients(coefficients, &filter);
					oldFrequency = currentFrequency;
				}
				buffer[i] = BIQUAD_FREQ_FILTER_II_process(buffer[i], &filter);
			}
		} else if (form == BI_FORM_I_TRANS) {
			for (size_t i = start; i < end; i++) {
				if (i > p2) {
					currentFrequency = p2Freq;
					indexOfPointBefore += numOfParamsPerBiquadPoint;
					indexOfPointAfter += numOfParamsPerBiquadPoint;
					p1 = points[indexOfPointBefore];
					p2 = points[indexOfPointAfter];
					p1Freq = points[indexOfPointBefore+1];
					p2Freq = points[indexOfPointAfter+1];
					t = ((double)i - p1) / (p2 - p1);
				} else {
					t = ((double)i - p1) / (p2 - p1);
					currentFrequency = p1Freq + t * (p2Freq - p1Freq);
				}
				if ((currentFrequency < 40) || fabsf(currentFrequency - oldFrequency) > 7) {
					CALCULATE_BIQUAD_FREQ_COEFFICIENTS(coefficients, sampleRate, currentFrequency, doubleQuality, type, gain, poleRadius);
					BIQUAD_FREQ_FILTER_setCoefficients(coefficients, &filter);
					oldFrequency = currentFrequency;
				}
				buffer[i] = BIQUAD_FREQ_FILTER_I_TRANS_process(buffer[i], &filter);
			}
		} else {
			for (size_t i = start; i < end; i++) {
				if (i > p2) {
					currentFrequency = p2Freq;
					indexOfPointBefore += numOfParamsPerBiquadPoint;
					indexOfPointAfter += numOfParamsPerBiquadPoint;
					p1 = points[indexOfPointBefore];
					p2 = points[indexOfPointAfter];
					p1Freq = points[indexOfPointBefore+1];
					p2Freq = points[indexOfPointAfter+1];
					t = ((double)i - p1) / (p2 - p1);
				} else {
					t = ((double)i - p1) / (p2 - p1);
					currentFrequency = p1Freq + t * (p2Freq - p1Freq);
				}
				if ((currentFrequency < 40) || fabsf(currentFrequency - oldFrequency) > 7) {
					CALCULATE_BIQUAD_FREQ_COEFFICIENTS(coefficients, sampleRate, currentFrequency, doubleQuality, type, gain, poleRadius);
					BIQUAD_FREQ_FILTER_setCoefficients(coefficients, &filter);
					oldFrequency = currentFrequency;
				}
				buffer[i] = BIQUAD_FREQ_FILTER_I_process(buffer[i], &filter);
			}
		}
		if (crossFade) {
			float x = 1.0f - samplesCrossfadeInverse;
			if (form == BI_FORM_II_TRANS) {
				for (size_t i = 1; i < samplesCrossfadeBiquadFrequencyFilter; i++) {
					buffer[i] = interpolate(buffer[i], BIQUAD_FREQ_FILTER_II_TRANS_process(buffer[i], &filter), x);
					x -= samplesCrossfadeInverse;
				}
			} else if (form == BI_FORM_II) {
				for (size_t i = 1; i < samplesCrossfadeBiquadFrequencyFilter; i++) {
					buffer[i] = interpolate(buffer[i], BIQUAD_FREQ_FILTER_II_process(buffer[i], &filter), x);
					x -= samplesCrossfadeInverse;
				}
			} else if (form == BI_FORM_I_TRANS) {
				for (size_t i = 1; i < samplesCrossfadeBiquadFrequencyFilter; i++) {
					buffer[i] = interpolate(buffer[i], BIQUAD_FREQ_FILTER_I_TRANS_process(buffer[i], &filter), x);
					x -= samplesCrossfadeInverse;
				}
			} else {
				for (size_t i = 1; i < samplesCrossfadeBiquadFrequencyFilter; i++) {
					buffer[i] = interpolate(buffer[i], BIQUAD_FREQ_FILTER_I_process(buffer[i], &filter), x);
					x -= samplesCrossfadeInverse;
				}
			}
		}
	} else {
		if (crossFade) {
			const int lenMinus = len - samplesCrossfadeBiquadFrequencyFilter;
			float x = samplesCrossfadeInverse;
			if (form == BI_FORM_II_TRANS) {
				for (size_t i = 1; i < samplesCrossfadeBiquadFrequencyFilter; i++) {
					buffer[i] = interpolate(buffer[i], BIQUAD_FREQ_FILTER_II_TRANS_process(buffer[i], &filter), x);
					x += samplesCrossfadeInverse;
				}
				for (size_t i = samplesCrossfadeBiquadFrequencyFilter; i < lenMinus; i++) {
					buffer[i] = BIQUAD_FREQ_FILTER_II_TRANS_process(buffer[i], &filter);
				}
				x = 1.0f - samplesCrossfadeInverse;
				for (size_t i = lenMinus; i < len; i++) {
					buffer[i] = interpolate(buffer[i], BIQUAD_FREQ_FILTER_II_TRANS_process(buffer[i], &filter), x);
					x -= samplesCrossfadeInverse;
				}
			} else if (form == BI_FORM_II) {
				for (size_t i = 1; i < samplesCrossfadeBiquadFrequencyFilter; i++) {
					buffer[i] = interpolate(buffer[i], BIQUAD_FREQ_FILTER_II_process(buffer[i], &filter), x);
					x += samplesCrossfadeInverse;
				}
				for (size_t i = samplesCrossfadeBiquadFrequencyFilter; i < lenMinus; i++) {
					buffer[i] = BIQUAD_FREQ_FILTER_II_process(buffer[i], &filter);
				}
				x = 1.0f - samplesCrossfadeInverse;
				for (size_t i = lenMinus; i < len; i++) {
					buffer[i] = interpolate(buffer[i], BIQUAD_FREQ_FILTER_II_process(buffer[i], &filter), x);
					x -= samplesCrossfadeInverse;
				}
			} else if (form == BI_FORM_I_TRANS) {
				for (size_t i = 1; i < samplesCrossfadeBiquadFrequencyFilter; i++) {
					buffer[i] = interpolate(buffer[i], BIQUAD_FREQ_FILTER_I_TRANS_process(buffer[i], &filter), x);
					x += samplesCrossfadeInverse;
				}
				for (size_t i = samplesCrossfadeBiquadFrequencyFilter; i < lenMinus; i++) {
					buffer[i] = BIQUAD_FREQ_FILTER_I_TRANS_process(buffer[i], &filter);
				}
				x = 1.0f - samplesCrossfadeInverse;
				for (size_t i = lenMinus; i < len; i++) {
					buffer[i] = interpolate(buffer[i], BIQUAD_FREQ_FILTER_I_TRANS_process(buffer[i], &filter), x);
					x -= samplesCrossfadeInverse;
				}
			} else {
				for (size_t i = 1; i < samplesCrossfadeBiquadFrequencyFilter; i++) {
					buffer[i] = interpolate(buffer[i], BIQUAD_FREQ_FILTER_I_process(buffer[i], &filter), x);
					x += samplesCrossfadeInverse;
				}
				for (size_t i = samplesCrossfadeBiquadFrequencyFilter; i < lenMinus; i++) {
					buffer[i] = BIQUAD_FREQ_FILTER_I_process(buffer[i], &filter);
				}
				x = 1.0f - samplesCrossfadeInverse;
				for (size_t i = lenMinus; i < len; i++) {
					buffer[i] = interpolate(buffer[i], BIQUAD_FREQ_FILTER_I_process(buffer[i], &filter), x);
					x -= samplesCrossfadeInverse;
				}
			}
		} else {
			if (form == BI_FORM_II_TRANS) {
				for (size_t i = 0; i < len; i++) {
					buffer[i] = BIQUAD_FREQ_FILTER_II_TRANS_process(buffer[i], &filter);
				}
			} else if (form == BI_FORM_II) {
				for (size_t i = 0; i < len; i++) {
					buffer[i] = BIQUAD_FREQ_FILTER_II_process(buffer[i], &filter);
				}
			} else if (form == BI_FORM_I_TRANS) {
				for (size_t i = 0; i < len; i++) {
					buffer[i] = BIQUAD_FREQ_FILTER_I_TRANS_process(buffer[i], &filter);
				}
			} else {
				for (size_t i = 0; i < len; i++) {
					buffer[i] = BIQUAD_FREQ_FILTER_I_process(buffer[i], &filter);
				}
			}
		}
	}
};

struct CustomFeedback1 {
	float x0, x1, x2, x3;
	float g;
};

inline float CustomFeedback1_process(float sample, struct CustomFeedback1* filter) {
	filter->g = filter->g + (fabsf(sample) - filter->g) * 0.01f;
	float x0 = filter->x3 * filter->g + sample;
	filter->x3 = filter->x2 * filter->g;
	filter->x2 = filter->x1 * filter->g;
	filter->x1 = x0 * filter->g;
	filter->x0 = x0;

	return x0;
};

EMSCRIPTEN_KEEPALIVE
void customfeedback1_process(float* buffer, int len) {
	if (len <= 1) return;

	struct CustomFeedback1 filter;

	filter.x0 = 0.0f;
	filter.x1 = 0.0f;
	filter.x2 = 0.0f;
	filter.x3 = 0.0f;
	filter.g = 0.0f;

	for (size_t i = 0; i < len; i++) {
		buffer[i] = CustomFeedback1_process(buffer[i], &filter);
	}
};

#ifndef __wasm_relaxed_simd__
#error "Relaxed SIMD flag is not being caught by the compiler!"
#endif

//#!/bin/sh
//# Compiles chorus.c to chorus.wasm + a minimal JS loader (chorus.js).
//#
//# -O3                     : full optimization (this is a hot numerical loop, worth it)
//# -s EXPORTED_FUNCTIONS    : only export chorus_process; keeps the module lean
//# -s EXPORTED_RUNTIME_METHODS=ccall : not actually used by glue.js (which calls
//#                            the exported function directly + uses HEAPF32 for
//#                            zero-copy), but harmless to leave in if you want
//#                            ccall available for debugging/console use
//# -s ALLOW_MEMORY_GROWTH=1 : lets the WASM heap grow if you process bigger
//#                            buffers than the default initial memory size;
//#                            without this, large buffers can fail to allocate
//# -s MODULARIZE=1 + EXPORT_NAME : wraps output as a factory function
//#                            (ChorusModule()) instead of a global, so it plays
//#                            nicely if you load multiple WASM modules or use
//#                            bundlers
//# --no-entry               : no main(), this is a library, not an executable
//emcc audio_effects.c -Ofast -fno-finite-math-only -msimd128 -mrelaxed-simd -flto -fno-rtti -s DISABLE_EXCEPTION_CATCHING=1 -s EXPORTED_FUNCTIONS="[\"_chorus_process\",\"_gain_process\",\"_biquadfrequencyfilter_i_process\",\"_customfeedback1_process\",\"_malloc\",\"_free\"]" -s EXPORTED_RUNTIME_METHODS="[\"ccall\",\"cwrap\",\"HEAPF32\"]" -s ALLOW_MEMORY_GROWTH=1 -s MODULARIZE=1 -s WASM=1 -s NO_DISABLE_EXCEPTION_CATCHING=1 -s EXPORT_NAME="ChorusModule" --no-entry -o audio_effects.js
